version: "3.8"

services:
  hanol-maria:
    container_name: hanol-maria
    image: mariadb:latest
    ports:
      - '3307:3306'
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --character-set-client-handshake=FALSE
      - --lower_case_table_names=1
    env_file: .env
    environment:
      - MYSQL_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MARIADB_DATABASE}
      - MYSQL_USER=${MARIADB_USER}
      - MYSQL_PASSWORD=${MARIADB_PASSWORD}
      - TZ=Asia/Seoul
    restart: always
    volumes:
      - ./db/mariadb:/var/lib/mysql
  hanol-redis:
    container_name: hanol-redis
    image: redis:7.0.12
    ports:
      - '6379:6379'
    env_file: .env
    command: redis-server --requirepass ${REDIS_PASSWORD} --port 6379
    restart: on-failure
  rabbitmq:
    container_name: hanol-rabbitmq
    image: rabbitmq:management
    env_file: .env
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASS}
    ports:
      - '5672:5672'
      - '15672:15672'