/* 루틴 데이터 */
INSERT INTO ROUTINE (routine_name, is_default, is_value_1, is_value_2, is_value_3, is_value_4, is_value_5, is_value_6) VALUES ('두피 전용 팩하기', 0, 1, 0, 0, 0, 0, 0);
INSERT INTO ROUTINE (routine_name, is_default, is_value_1, is_value_2, is_value_3, is_value_4, is_value_5, is_value_6) VALUES ('따끈하게 적신 스팀 타월로 머리 찜질하기', 0, 1, 0, 0, 0, 0, 0);
INSERT INTO ROUTINE (routine_name, is_default, is_value_1, is_value_2, is_value_3, is_value_4, is_value_5, is_value_6) VALUES ('호호바 오일 사용해서 머리 감기', 0, 1, 0, 0, 0, 0, 0);
INSERT INTO ROUTINE (routine_name, is_default, is_value_1, is_value_2, is_value_3, is_value_4, is_value_5, is_value_6) VALUES ('샴푸 후 두피에서 모발 순으로 건조하기', 1, 0, 0, 0, 0, 0, 0);
INSERT INTO ROUTINE (routine_name, is_default, is_value_1, is_value_2, is_value_3, is_value_4, is_value_5, is_value_6) VALUES ('피부가 회복되는 오후 10시에서 새벽 2시에 샴푸하기', 0, 0, 1, 0, 0, 0, 0);
INSERT INTO ROUTINE (routine_name, is_default, is_value_1, is_value_2, is_value_3, is_value_4, is_value_5, is_value_6) VALUES ('샴푸 시 2회에 걸쳐 꼼꼼하게 두피의 노폐물 씻어내기', 0, 0, 1, 0, 0, 0, 0);
INSERT INTO ROUTINE (routine_name, is_default, is_value_1, is_value_2, is_value_3, is_value_4, is_value_5, is_value_6) VALUES ('천연계면활성제, 자연 유래 성분을 이용한 저자극 샴푸 이용', 0, 0, 1, 0, 0, 0, 0);
INSERT INTO ROUTINE (routine_name, is_default, is_value_1, is_value_2, is_value_3, is_value_4, is_value_5, is_value_6) VALUES ('손가락 지문 부분을 이용해서 머리 감기', 0, 0, 1, 0, 0, 0, 0);
INSERT INTO ROUTINE (routine_name, is_default, is_value_1, is_value_2, is_value_3, is_value_4, is_value_5, is_value_6) VALUES ('하루에 2번 머리 감기', 0, 0, 1, 0, 0, 0, 0);
INSERT INTO ROUTINE (routine_name, is_default, is_value_1, is_value_2, is_value_3, is_value_4, is_value_5, is_value_6) VALUES ('약산성 샴푸 쓰기', 0, 0, 0, 1, 0, 0, 0);
INSERT INTO ROUTINE (routine_name, is_default, is_value_1, is_value_2, is_value_3, is_value_4, is_value_5, is_value_6) VALUES ('스트레스나 과로 피하기', 0, 0, 1, 0, 1, 1, 0);
INSERT INTO ROUTINE (routine_name, is_default, is_value_1, is_value_2, is_value_3, is_value_4, is_value_5, is_value_6) VALUES ('스프레이, 젤 등 유분 함량 많은 제품 피하기', 0, 0, 0, 1, 0, 0, 0);
INSERT INTO ROUTINE (routine_name, is_default, is_value_1, is_value_2, is_value_3, is_value_4, is_value_5, is_value_6) VALUES ('샴푸 후 머리 바로 말리기', 0, 0, 1, 1, 0, 0, 0);
INSERT INTO ROUTINE (routine_name, is_default, is_value_1, is_value_2, is_value_3, is_value_4, is_value_5, is_value_6) VALUES ('염색 피하기', 0, 0, 0, 1, 0, 0, 0);
INSERT INTO ROUTINE (routine_name, is_default, is_value_1, is_value_2, is_value_3, is_value_4, is_value_5, is_value_6) VALUES ('베개 커버 교체하기', 0, 0, 0, 1, 0, 0, 0);
INSERT INTO ROUTINE (routine_name, is_default, is_value_1, is_value_2, is_value_3, is_value_4, is_value_5, is_value_6) VALUES ('드라이기, 고데기 사용하지 않기', 1, 0, 0, 0, 0, 0, 0);
INSERT INTO ROUTINE (routine_name, is_default, is_value_1, is_value_2, is_value_3, is_value_4, is_value_5, is_value_6) VALUES ('머리 헹굴 때 레몬즙 1~2 방울 (비타민 C)', 0, 0, 1, 0, 0, 0, 0);
INSERT INTO ROUTINE (routine_name, is_default, is_value_1, is_value_2, is_value_3, is_value_4, is_value_5, is_value_6) VALUES ('기름진 음식 자제하기', 0, 0, 0, 0, 0, 1, 0);
INSERT INTO ROUTINE (routine_name, is_default, is_value_1, is_value_2, is_value_3, is_value_4, is_value_5, is_value_6) VALUES ('니조랄 성분인 케토코나졸이 들어간 샴푸(향진균 약용 샴푸) 일주일에 2~3번 사용', 0, 0, 0, 0, 0, 1, 0);
INSERT INTO ROUTINE (routine_name, is_default, is_value_1, is_value_2, is_value_3, is_value_4, is_value_5, is_value_6) VALUES ('두피 마사지하기', 1, 0, 0, 0, 0, 0, 0);
INSERT INTO ROUTINE (routine_name, is_default, is_value_1, is_value_2, is_value_3, is_value_4, is_value_5, is_value_6) VALUES ('차가운 바람으로 머리 말리기', 1, 0, 0, 0, 0, 0, 0);
INSERT INTO ROUTINE (routine_name, is_default, is_value_1, is_value_2, is_value_3, is_value_4, is_value_5, is_value_6) VALUES ('모낭염 연고 바르기(에스로반 or 후시딘)', 0, 0, 0, 0, 1, 0, 0);
INSERT INTO ROUTINE (routine_name, is_default, is_value_1, is_value_2, is_value_3, is_value_4, is_value_5, is_value_6) VALUES ('징크피리치온 성분이 함유된 샴푸 사용', 0, 0, 0, 0, 1, 0, 0);
INSERT INTO ROUTINE (routine_name, is_default, is_value_1, is_value_2, is_value_3, is_value_4, is_value_5, is_value_6) VALUES ('미노사이클린 성분의 항생제 먹기', 0, 0, 0, 0, 1, 0, 0);
INSERT INTO ROUTINE (routine_name, is_default, is_value_1, is_value_2, is_value_3, is_value_4, is_value_5, is_value_6) VALUES ('맥주 효모로 머리 감기', 0, 0, 0, 0, 0, 0, 1);
INSERT INTO ROUTINE (routine_name, is_default, is_value_1, is_value_2, is_value_3, is_value_4, is_value_5, is_value_6) VALUES ('비오틴 영양제 먹기', 0, 0, 0, 0, 0, 0, 1);
INSERT INTO ROUTINE (routine_name, is_default, is_value_1, is_value_2, is_value_3, is_value_4, is_value_5, is_value_6) VALUES ('금연하기', 1, 0, 0, 0, 0, 0, 0);
INSERT INTO ROUTINE (routine_name, is_default, is_value_1, is_value_2, is_value_3, is_value_4, is_value_5, is_value_6) VALUES ('무리한 다이어트 피하기', 0, 0, 0, 0, 0, 0, 1);
INSERT INTO ROUTINE (routine_name, is_default, is_value_1, is_value_2, is_value_3, is_value_4, is_value_5, is_value_6) VALUES ('11시 이전에 잠들기', 1, 0, 0, 0, 0, 0, 0);
INSERT INTO ROUTINE (routine_name, is_default, is_value_1, is_value_2, is_value_3, is_value_4, is_value_5, is_value_6) VALUES ('단백질 섭취하기 (이소플라본 : 콩, 두부, 콩나물)', 0, 0, 0, 0, 0, 0, 1);
INSERT INTO ROUTINE (routine_name, is_default, is_value_1, is_value_2, is_value_3, is_value_4, is_value_5, is_value_6) VALUES ('영양제 먹기 (미녹시딜, 판시딜 )', 0, 0, 0, 0, 0, 0, 1);
INSERT INTO ROUTINE (routine_name, is_default, is_value_1, is_value_2, is_value_3, is_value_4, is_value_5, is_value_6) VALUES ('탈모 약 복용하기', 0, 0, 0, 0, 0, 0, 1);
INSERT INTO ROUTINE (routine_name, is_default, is_value_1, is_value_2, is_value_3, is_value_4, is_value_5, is_value_6) VALUES ('탈모 약 바르기', 0, 0, 0, 0, 0, 0, 1);
INSERT INTO ROUTINE (routine_name, is_default, is_value_1, is_value_2, is_value_3, is_value_4, is_value_5, is_value_6) VALUES ('금주하기', 1, 0, 0, 0, 0, 0, 0);
INSERT INTO ROUTINE (routine_name, is_default, is_value_1, is_value_2, is_value_3, is_value_4, is_value_5, is_value_6) VALUES ('아누카 사과 먹기', 0, 0, 0, 0, 0, 0, 1);
